project_id = "navperzideudgemourrw"

[functions.create-admin]
verify_jwt = false

[functions.update-user-password]
verify_jwt = true

[functions.telegram-auth]
verify_jwt = false

[functions.admin-login-as-user]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-all-users]
verify_jwt = true
